# Generated by Django 3.1.7 on 2021-03-10 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accommodation', '0002_auto_20210305_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='option',
            field=models.ManyToManyField(through='accommodation.RoomOption', to='accommodation.Option'),
        ),
    ]
