# Generated by Django 3.1.7 on 2021-03-04 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accommodation', '0001_initial'),
        ('flight', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccommodationOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('guest', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=300)),
            ],
            options={
                'db_table': 'accommodation_orders',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'order_statuses',
            },
        ),
        migrations.CreateModel(
            name='Reservations',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accommodation_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='order.accommodationorder')),
                ('room_fluctuation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accommodation.roomfluctuation')),
            ],
            options={
                'db_table': 'reservations',
            },
        ),
        migrations.CreateModel(
            name='FlightOrders',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=30)),
                ('passenger', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('serial_number', models.CharField(max_length=300)),
                ('flight_price', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='flight.flightprice')),
                ('order_status', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.orderstatus')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user')),
            ],
            options={
                'db_table': 'flight_orders',
            },
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='order_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='order.orderstatus'),
        ),
        migrations.AddField(
            model_name='accommodationorder',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user.user'),
        ),
    ]
