# Generated by Django 3.1.7 on 2021-03-11 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_user_kakao_id'),
        ('flight', '0001_initial'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FlightOrders',
            new_name='FlightOrder',
        ),
    ]
